import { api, ApiError, userFacingError, type DocumentVersion, type PDFMetadata } from "@pdf-studio/api-client";
import { Button, Card } from "@pdf-studio/ui";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { capabilitiesQuery, documentsQuery, queryKeys } from "../../api/queries";
import { ErrorState, LoadingState } from "../../components/async-state";

export type PhaseOneToolKind = "protect" | "unlock" | "watermark" | "page-numbers" | "header-footer" | "metadata";
const copy: Record<PhaseOneToolKind, { eyebrow: string; title: string; description: string; action: string }> = {
  protect: { eyebrow: "Security", title: "Protect PDF", description: "Require an open password and configure common reader permissions with modern encryption.", action: "Protect PDF" },
  unlock: { eyebrow: "Security", title: "Unlock PDF", description: "Remove encryption only when you provide a valid credential.", action: "Unlock PDF" },
  watermark: { eyebrow: "Edit & enhance", title: "Watermark PDF", description: "Place a text or JPEG watermark on selected pages with a lightweight live preview.", action: "Apply watermark" },
  "page-numbers": { eyebrow: "Edit & enhance", title: "Page Numbers", description: "Add consistent numbering with ranges, offsets, prefixes, and placement presets.", action: "Add page numbers" },
  "header-footer": { eyebrow: "Edit & enhance", title: "Header & Footer", description: "Add independent left, center, and right content with document variables.", action: "Add header & footer" },
  metadata: { eyebrow: "Document", title: "PDF Metadata", description: "Edit standard embedded fields while leaving unrelated document content untouched.", action: "Save metadata" },
};

const defaults = { fontSize: 36, opacity: 0.25, rotation: -35, horizontal: "center", vertical: "center", pageRange: "", foreground: true, scale: 0.25, position: "bottom-center", startNumber: 1, margin: 32, prefix: "", suffix: "", includeTotal: false, skipFirst: false };

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-ink"><span>{label}</span><span className="mt-1 block">{children}</span></label>; }
function TextInput(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="form-control" />; }

export function PhaseOneToolPage({ kind }: { kind: PhaseOneToolKind }) {
  const capabilities = useQuery(capabilitiesQuery);
  const documents = useQuery(documentsQuery);
  const queryClient = useQueryClient();
  const [documentId, setDocumentId] = useState("");
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showPassword, setShowPassword] = useState(false);
  const [options, setOptions] = useState(defaults); const [watermarkType, setWatermarkType] = useState<"text" | "image">("text"); const [watermarkText, setWatermarkText] = useState("CONFIDENTIAL"); const [image, setImage] = useState<File>();
  const [permissions, setPermissions] = useState({ printing: true, copying: false, modification: false, annotation: false, formFilling: true, assembly: false });
  const [header, setHeader] = useState({ left: "", center: "", right: "{date}" }); const [footer, setFooter] = useState({ left: "Confidential", center: "", right: "Page {page} of {pages}" });
  const [metadata, setMetadata] = useState<PDFMetadata>({ title: "", author: "", subject: "", keywords: "" });
  const [confirmSignatures, setConfirmSignatures] = useState(false);
  const metadataQuery = useQuery({ queryKey: ["documents", documentId, "metadata"], queryFn: ({ signal }) => api.metadata(documentId, signal), enabled: Boolean(documentId) });
  useEffect(() => { if (metadataQuery.data) setMetadata(metadataQuery.data.metadata); }, [metadataQuery.data]);
  const mutation = useMutation({ mutationFn: async () => {
    if (kind === "metadata") return api.updateMetadata(documentId, metadata, confirmSignatures);
    if (kind === "watermark" && watermarkType === "image" && image) return api.watermarkImage(documentId, image, { ...Object.fromEntries(Object.entries(options).map(([key, value]) => [key, String(value)])), confirmSignatures: String(confirmSignatures) });
    const payload: Record<string, unknown> = { documentId, confirmSignatures };
    if (kind === "protect") Object.assign(payload, permissions, { password, confirmPassword });
    if (kind === "unlock") Object.assign(payload, { password });
    if (kind === "watermark") Object.assign(payload, options, { watermarkType: "text", text: watermarkText });
    if (kind === "page-numbers") Object.assign(payload, options);
    if (kind === "header-footer") Object.assign(payload, { header, footer, fontSize: options.fontSize, margin: options.margin, pageRange: options.pageRange, skipFirst: options.skipFirst });
    return api.process(kind, payload);
  }, onSuccess: async () => { setPassword(""); setConfirmPassword(""); await Promise.all([queryClient.invalidateQueries({ queryKey: queryKeys.documents }), queryClient.invalidateQueries({ queryKey: queryKeys.versions(documentId) })]); } });
  const result = mutation.data as { version?: DocumentVersion; document?: { id: string } } | undefined;
  const signatureRequired = Boolean(metadataQuery.data?.information.signed || (mutation.error instanceof ApiError && mutation.error.code === "SIGNATURE_CONFIRMATION_REQUIRED"));
  const feature = kind === "page-numbers" ? "pageNumbers" : kind === "header-footer" ? "headerFooter" : kind;
  const available = capabilities.data?.features[feature as keyof typeof capabilities.data.features] ?? false;
  const reason = capabilities.data?.tools.qpdf.reason ?? capabilities.data?.tools.pdfinfo.reason ?? "Required backend processing is unavailable.";
  const valid = useMemo(() => { if (!documentId) return false; if (kind === "protect") return password.length > 0 && password === confirmPassword; if (kind === "unlock") return password.length > 0; if (kind === "watermark") return watermarkType === "text" ? watermarkText.trim().length > 0 : Boolean(image); return true; }, [confirmPassword, documentId, image, kind, password, watermarkText, watermarkType]);
  if (capabilities.isPending || documents.isPending) return <LoadingState />;
  if (capabilities.isError) return <ErrorState error={capabilities.error} />;
  if (documents.isError) return <ErrorState error={documents.error} />;
  const info = copy[kind];
  const submit = (event: FormEvent) => { event.preventDefault(); if (valid && available && !mutation.isPending) mutation.mutate(); };
  return <main className="page-shell py-12"><header className="max-w-3xl"><p className="eyebrow">{info.eyebrow}</p><h1 className="display-title mt-3 text-5xl text-ink sm:text-6xl">{info.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted">{info.description}</p></header>
    {!available ? <Card className="mt-7 border-accent bg-accent-soft p-5"><strong>Capability unavailable</strong><p className="mt-1 text-sm text-muted">{reason}</p></Card> : null}
    <form onSubmit={submit} className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><Card className="space-y-5 p-6 sm:p-8"><Field label="Document"><select className="form-control" value={documentId} onChange={(event) => { setDocumentId(event.target.value); mutation.reset(); }}><option value="">Choose a recent PDF</option>{documents.data.documents.map((item) => <option key={item.id} value={item.id}>{item.originalName}</option>)}</select></Field>
      {(kind === "protect" || kind === "unlock") ? <><Field label={kind === "protect" ? "Open password" : "Current password"}><span className="relative block"><TextInput type={showPassword ? "text" : "password"} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} aria-invalid={kind === "protect" && Boolean(confirmPassword) && password !== confirmPassword} /><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-2.5 rounded p-1" aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff className="size-5" /> : <Eye className="size-5" />}</button></span></Field>{kind === "protect" ? <><Field label="Confirm password"><TextInput type={showPassword ? "text" : "password"} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} /></Field>{password !== confirmPassword && confirmPassword ? <p className="text-sm text-red-700" role="alert">Passwords do not match.</p> : null}<fieldset><legend className="text-sm font-black">Permissions</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(permissions).map(([key, value]) => <label key={key} className="flex items-center gap-2 text-sm capitalize"><input type="checkbox" checked={value} onChange={(event) => setPermissions((current) => ({ ...current, [key]: event.target.checked }))} />{key.replace(/([A-Z])/g, " $1")}</label>)}</div><p className="mt-3 text-xs leading-5 text-muted">Reader permissions are policy hints, not a guarantee against every form of content extraction.</p></fieldset></> : null}</> : null}
      {kind === "watermark" ? <><fieldset><legend className="text-sm font-black">Watermark type</legend><div className="mt-2 flex gap-4"><label><input type="radio" checked={watermarkType === "text"} onChange={() => setWatermarkType("text")} /> Text</label><label><input type="radio" checked={watermarkType === "image"} onChange={() => setWatermarkType("image")} /> Image (JPEG)</label></div></fieldset>{watermarkType === "text" ? <><Field label="Text"><TextInput value={watermarkText} maxLength={200} onChange={(event) => setWatermarkText(event.target.value)} /></Field><div className="flex flex-wrap gap-2">{["CONFIDENTIAL","DRAFT","COPY","INTERNAL","APPROVED","DO NOT DISTRIBUTE"].map((value) => <button type="button" key={value} onClick={() => setWatermarkText(value)} className="rounded-full border border-line px-3 py-1.5 text-xs font-bold hover:border-accent">{value}</button>)}</div></> : <Field label="JPEG logo"><input type="file" accept="image/jpeg" onChange={(event) => setImage(event.target.files?.[0])} className="block w-full text-sm" /></Field>}<RangeOptions options={options} setOptions={setOptions} watermark /></> : null}
      {kind === "page-numbers" ? <><Field label="Position"><select className="form-control" value={options.position} onChange={(event) => setOptions({ ...options, position: event.target.value })}>{["top-left","top-center","top-right","bottom-left","bottom-center","bottom-right"].map((value) => <option key={value} value={value}>{value.replace("-", " ")}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Starting number"><TextInput type="number" min={0} value={options.startNumber} onChange={(event) => setOptions({ ...options, startNumber: event.target.valueAsNumber })} /></Field><Field label="Page range (optional)"><TextInput placeholder="2-8,10" value={options.pageRange} onChange={(event) => setOptions({ ...options, pageRange: event.target.value })} /></Field><Field label="Prefix"><TextInput placeholder="Page " value={options.prefix} onChange={(event) => setOptions({ ...options, prefix: event.target.value })} /></Field><Field label="Suffix"><TextInput placeholder=" -" value={options.suffix} onChange={(event) => setOptions({ ...options, suffix: event.target.value })} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={options.includeTotal} onChange={(event) => setOptions({ ...options, includeTotal: event.target.checked })} />Include total pages</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={options.skipFirst} onChange={(event) => setOptions({ ...options, skipFirst: event.target.checked })} />Skip first page</label></> : null}
      {kind === "header-footer" ? <><BandFields title="Header" value={header} onChange={setHeader} /><BandFields title="Footer" value={footer} onChange={setFooter} /><p className="text-xs text-muted">Variables: {`{page} {pages} {filename} {date}`}</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Page range (optional)"><TextInput placeholder="1-5,8" value={options.pageRange} onChange={(event) => setOptions({ ...options, pageRange: event.target.value })} /></Field><Field label="Font size"><TextInput type="number" min={6} max={48} value={options.fontSize} onChange={(event) => setOptions({ ...options, fontSize: event.target.valueAsNumber })} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={options.skipFirst} onChange={(event) => setOptions({ ...options, skipFirst: event.target.checked })} />Skip first page</label></> : null}
      {kind === "metadata" ? metadataQuery.isPending && documentId ? <LoadingState label="Reading embedded metadata…" /> : <div className="grid gap-4 sm:grid-cols-2">{(["title","author","subject","keywords"] as const).map((field) => <Field key={field} label={field[0].toUpperCase()+field.slice(1)}><TextInput value={metadata[field]} onChange={(event) => setMetadata({ ...metadata, [field]: event.target.value })} /></Field>)}</div> : null}
      {signatureRequired ? <label className="flex gap-3 rounded-xl border border-amber-400 bg-amber-50 p-4 text-sm leading-6"><input type="checkbox" checked={confirmSignatures} onChange={(event) => setConfirmSignatures(event.target.checked)} /><span><strong className="block text-amber-950">This PDF contains digital signatures.</strong>Modifying it may invalidate existing signatures. Check to confirm before continuing.</span></label> : null}
      <Button type="submit" disabled={!available || !valid || mutation.isPending || Boolean(signatureRequired && !confirmSignatures)}>{mutation.isPending ? "Processing…" : info.action}</Button>{mutation.isPending ? <p className="text-sm text-muted" role="status">Preparing… Processing… Saving a new version…</p> : null}{mutation.isError ? <p className="text-sm text-red-700" role="alert">{userFacingError(mutation.error)} The original is unchanged.</p> : null}{mutation.isSuccess ? <p className="text-sm text-emerald-700" role="status">Complete. The result is available in Recent Files and document history.</p> : null}</Card>
      <aside className="space-y-4">{kind === "watermark" ? <Card className="p-5"><h2 className="font-black">Representative preview</h2><div className="relative mt-4 aspect-[3/4] overflow-hidden rounded-xl border border-line bg-white p-6 shadow-inner"><div className="space-y-3 opacity-20">{Array.from({length:9},(_,i)=><div key={i} className="h-2 rounded bg-ink" style={{width:`${60+(i%3)*12}%`}} />)}</div><div className="absolute inset-0 flex items-center justify-center overflow-hidden"><span className="max-w-full font-black text-accent" style={{fontSize:`${Math.max(14,Math.min(options.fontSize,48))}px`,opacity:options.opacity,transform:`rotate(${options.rotation}deg)`}}>{watermarkType === "text" ? watermarkText : image?.name ?? "JPEG logo"}</span></div></div><p className="mt-3 text-xs text-muted">Preview is client-side; final placement is generated and validated by the backend.</p></Card> : null}{kind === "metadata" && metadataQuery.data ? <Card className="p-5"><h2 className="font-black">Document information</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-muted">Pages</dt><dd>{metadataQuery.data.information.pageCount ?? "Unknown"}</dd></div><div><dt className="text-muted">File size</dt><dd>{metadataQuery.data.information.fileSize.toLocaleString()} bytes</dd></div><div><dt className="text-muted">Modified</dt><dd>{new Date(metadataQuery.data.information.modifiedAt).toLocaleString()}</dd></div></dl></Card> : null}<Card className="p-5"><ShieldCheck className="size-6 text-accent" /><h2 className="mt-3 font-black">Original-safe</h2><p className="mt-1 text-sm leading-6 text-muted">Every successful operation validates a temporary PDF and atomically saves a new version.</p>{result?.version && result.document ? <Button asChild variant="secondary" className="mt-4 w-full"><a href={api.versionContentUrl(result.document.id,result.version.id)} download><Download className="size-4" />Download result</a></Button> : null}</Card></aside></form></main>;
}

function RangeOptions({ options, setOptions, watermark = false }: { options: typeof defaults; setOptions: (value: typeof defaults) => void; watermark?: boolean }) { return <div className="grid gap-4 sm:grid-cols-2"><Field label="Opacity"><TextInput type="range" min="0.05" max="1" step="0.05" value={options.opacity} onChange={(event) => setOptions({ ...options, opacity: event.target.valueAsNumber })} /></Field><Field label={watermark ? "Rotation" : "Font size"}><TextInput type="number" min={watermark ? -180 : 6} max={watermark ? 180 : 144} value={watermark ? options.rotation : options.fontSize} onChange={(event) => setOptions({ ...options, [watermark ? "rotation" : "fontSize"]: event.target.valueAsNumber })} /></Field><Field label="Horizontal"><select className="form-control" value={options.horizontal} onChange={(event) => setOptions({ ...options, horizontal: event.target.value })}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></Field><Field label="Vertical"><select className="form-control" value={options.vertical} onChange={(event) => setOptions({ ...options, vertical: event.target.value })}><option value="top">Top</option><option value="center">Center</option><option value="bottom">Bottom</option></select></Field><Field label="Page range (optional)"><TextInput placeholder="1-3,5" value={options.pageRange} onChange={(event) => setOptions({ ...options, pageRange: event.target.value })} /></Field>{watermark ? <Field label="Scale (image)"><TextInput type="range" min="0.05" max="1" step="0.05" value={options.scale} onChange={(event) => setOptions({ ...options, scale: event.target.valueAsNumber })} /></Field> : null}</div>; }
function BandFields({ title, value, onChange }: { title: string; value: {left:string;center:string;right:string}; onChange: (value:{left:string;center:string;right:string}) => void }) { return <fieldset><legend className="text-sm font-black">{title}</legend><div className="mt-2 grid gap-3 sm:grid-cols-3">{(["left","center","right"] as const).map((field)=><TextInput key={field} aria-label={`${title} ${field}`} placeholder={field} value={value[field]} onChange={(event)=>onChange({...value,[field]:event.target.value})} />)}</div></fieldset>; }
