// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearDocumentVersionParents = `-- name: ClearDocumentVersionParents :exec
UPDATE document_versions
SET parent_version_id = NULL
WHERE document_id = $1
`

func (q *Queries) ClearDocumentVersionParents(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentVersionParents, documentID)
	return err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OriginalName   string    `json:"original_name"`
	MediaType      string    `json:"media_type"`
	ByteSize       int64     `json:"byte_size"`
	PageCount      *int32    `json:"page_count"`
	OriginalPath   string    `json:"original_path"`
	ChecksumSha256 string    `json:"checksum_sha256"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.OriginalName,
		arg.MediaType,
		arg.ByteSize,
		arg.PageCount,
		arg.OriginalPath,
		arg.ChecksumSha256,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.MediaType,
		&i.ByteSize,
		&i.PageCount,
		&i.OriginalPath,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
    id, document_id, parent_version_id, operation, storage_path, byte_size, checksum_sha256, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8::text::jsonb
)
RETURNING id, document_id, parent_version_id, operation, storage_path, byte_size, checksum_sha256, metadata, created_at
`

type CreateDocumentVersionParams struct {
	ID              uuid.UUID  `json:"id"`
	DocumentID      uuid.UUID  `json:"document_id"`
	ParentVersionID *uuid.UUID `json:"parent_version_id"`
	Operation       string     `json:"operation"`
	StoragePath     string     `json:"storage_path"`
	ByteSize        int64      `json:"byte_size"`
	ChecksumSha256  string     `json:"checksum_sha256"`
	Metadata        string     `json:"metadata"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.ParentVersionID,
		arg.Operation,
		arg.StoragePath,
		arg.ByteSize,
		arg.ChecksumSha256,
		arg.Metadata,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentVersionID,
		&i.Operation,
		&i.StoragePath,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentVersions = `-- name: DeleteDocumentVersions :exec
DELETE FROM document_versions WHERE document_id = $1
`

func (q *Queries) DeleteDocumentVersions(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentVersions, documentID)
	return err
}

const deleteProcessingRunsForDocument = `-- name: DeleteProcessingRunsForDocument :exec
DELETE FROM processing_runs WHERE document_id = $1
`

func (q *Queries) DeleteProcessingRunsForDocument(ctx context.Context, documentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProcessingRunsForDocument, documentID)
	return err
}

const getDeletedDocument = `-- name: GetDeletedDocument :one
SELECT id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at FROM documents WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetDeletedDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDeletedDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.MediaType,
		&i.ByteSize,
		&i.PageCount,
		&i.OriginalPath,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at FROM documents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.MediaType,
		&i.ByteSize,
		&i.PageCount,
		&i.OriginalPath,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, parent_version_id, operation, storage_path, byte_size, checksum_sha256, metadata, created_at FROM document_versions
WHERE document_id = $1 AND id = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.ID)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentVersionID,
		&i.Operation,
		&i.StoragePath,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDocumentVersion = `-- name: GetLatestDocumentVersion :one
SELECT id, document_id, parent_version_id, operation, storage_path, byte_size, checksum_sha256, metadata, created_at FROM document_versions
WHERE document_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestDocumentVersion(ctx context.Context, documentID uuid.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getLatestDocumentVersion, documentID)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentVersionID,
		&i.Operation,
		&i.StoragePath,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteDocument = `-- name: HardDeleteDocument :execrows
DELETE FROM documents WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeletedDocuments = `-- name: ListDeletedDocuments :many
SELECT id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at FROM documents
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListDeletedDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDeletedDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.MediaType,
			&i.ByteSize,
			&i.PageCount,
			&i.OriginalPath,
			&i.ChecksumSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, parent_version_id, operation, storage_path, byte_size, checksum_sha256, metadata, created_at FROM document_versions
WHERE document_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDocumentVersions(ctx context.Context, documentID uuid.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParentVersionID,
			&i.Operation,
			&i.StoragePath,
			&i.ByteSize,
			&i.ChecksumSha256,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at FROM documents
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.MediaType,
			&i.ByteSize,
			&i.PageCount,
			&i.OriginalPath,
			&i.ChecksumSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDocument = `-- name: RestoreDocument :execrows
UPDATE documents
SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameDocument = `-- name: RenameDocument :one
UPDATE documents
SET original_name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, original_name, media_type, byte_size, page_count, original_path, checksum_sha256, created_at, updated_at, deleted_at
`

type RenameDocumentParams struct {
	ID           uuid.UUID `json:"id"`
	OriginalName string    `json:"original_name"`
}

func (q *Queries) RenameDocument(ctx context.Context, arg RenameDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, renameDocument, arg.ID, arg.OriginalName)
	var i Document
	err := row.Scan(&i.ID, &i.OriginalName, &i.MediaType, &i.ByteSize, &i.PageCount, &i.OriginalPath, &i.ChecksumSha256, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt)
	return i, err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :execrows
UPDATE documents
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentPageCount = `-- name: UpdateDocumentPageCount :exec
UPDATE documents SET page_count = $2, updated_at = now() WHERE id = $1
`

type UpdateDocumentPageCountParams struct {
	ID        uuid.UUID `json:"id"`
	PageCount *int32    `json:"page_count"`
}

func (q *Queries) UpdateDocumentPageCount(ctx context.Context, arg UpdateDocumentPageCountParams) error {
	_, err := q.db.Exec(ctx, updateDocumentPageCount, arg.ID, arg.PageCount)
	return err
}
