// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID             uuid.UUID  `json:"id"`
	OriginalName   string     `json:"original_name"`
	MediaType      string     `json:"media_type"`
	ByteSize       int64      `json:"byte_size"`
	PageCount      *int32     `json:"page_count"`
	OriginalPath   string     `json:"original_path"`
	ChecksumSha256 string     `json:"checksum_sha256"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type DocumentVersion struct {
	ID              uuid.UUID  `json:"id"`
	DocumentID      uuid.UUID  `json:"document_id"`
	ParentVersionID *uuid.UUID `json:"parent_version_id"`
	Operation       string     `json:"operation"`
	StoragePath     string     `json:"storage_path"`
	ByteSize        int64      `json:"byte_size"`
	ChecksumSha256  string     `json:"checksum_sha256"`
	Metadata        []byte     `json:"metadata"`
	CreatedAt       time.Time  `json:"created_at"`
}

type ProcessingRun struct {
	ID         uuid.UUID  `json:"id"`
	DocumentID *uuid.UUID `json:"document_id"`
	Operation  string     `json:"operation"`
	Status     string     `json:"status"`
	Input      []byte     `json:"input"`
	Output     []byte     `json:"output"`
	ErrorCode  *string    `json:"error_code"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
}
