// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processing.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProcessingRun = `-- name: CreateProcessingRun :one
INSERT INTO processing_runs (id, document_id, operation, status, input)
VALUES ($1, $2, $3, 'running', $4::text::jsonb)
RETURNING id, document_id, operation, status, input, output, error_code, started_at, finished_at
`

type CreateProcessingRunParams struct {
	ID         uuid.UUID  `json:"id"`
	DocumentID *uuid.UUID `json:"document_id"`
	Operation  string     `json:"operation"`
	Input      string     `json:"input"`
}

func (q *Queries) CreateProcessingRun(ctx context.Context, arg CreateProcessingRunParams) (ProcessingRun, error) {
	row := q.db.QueryRow(ctx, createProcessingRun,
		arg.ID,
		arg.DocumentID,
		arg.Operation,
		arg.Input,
	)
	var i ProcessingRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Operation,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishProcessingRun = `-- name: FinishProcessingRun :exec
UPDATE processing_runs
SET status = $1, output = $2::text::jsonb,
    error_code = $3, finished_at = now()
WHERE id = $4
`

type FinishProcessingRunParams struct {
	Status    string    `json:"status"`
	Output    string    `json:"output"`
	ErrorCode *string   `json:"error_code"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) FinishProcessingRun(ctx context.Context, arg FinishProcessingRunParams) error {
	_, err := q.db.Exec(ctx, finishProcessingRun,
		arg.Status,
		arg.Output,
		arg.ErrorCode,
		arg.ID,
	)
	return err
}
