/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllToolsRouteImport } from './routes/all-tools'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as HeaderFooterRouteImport } from './routes/header-footer'
import { Route as MergeRouteImport } from './routes/merge'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as PageNumbersRouteImport } from './routes/page-numbers'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SplitRouteImport } from './routes/split'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as EditIndexRouteImport } from './routes/edit/index'
import { Route as EditSessionIdRouteImport } from './routes/edit/$sessionId'
import { Route as ToolsCompressRouteImport } from './routes/tools/compress'
import { Route as ToolsMergeRouteImport } from './routes/tools/merge'
import { Route as ToolsOcrRouteImport } from './routes/tools/ocr'
import { Route as ToolsSplitRouteImport } from './routes/tools/split'
import { Route as DocumentsDocumentIdIndexRouteImport } from './routes/documents/$documentId/index'
import { Route as DocumentsDocumentIdEditRouteImport } from './routes/documents/$documentId/edit'
import { Route as DocumentsDocumentIdOrganizeRouteImport } from './routes/documents/$documentId/organize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllToolsRoute = AllToolsRouteImport.update({
  id: '/all-tools',
  path: '/all-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderFooterRoute = HeaderFooterRouteImport.update({
  id: '/header-footer',
  path: '/header-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeRoute = MergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const PageNumbersRoute = PageNumbersRouteImport.update({
  id: '/page-numbers',
  path: '/page-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditSessionIdRoute = EditSessionIdRouteImport.update({
  id: '/edit/$sessionId',
  path: '/edit/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressRoute = ToolsCompressRouteImport.update({
  id: '/tools/compress',
  path: '/tools/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergeRoute = ToolsMergeRouteImport.update({
  id: '/tools/merge',
  path: '/tools/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOcrRoute = ToolsOcrRouteImport.update({
  id: '/tools/ocr',
  path: '/tools/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitRoute = ToolsSplitRouteImport.update({
  id: '/tools/split',
  path: '/tools/split',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdIndexRoute =
  DocumentsDocumentIdIndexRouteImport.update({
    id: '/documents/$documentId/',
    path: '/documents/$documentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsDocumentIdEditRoute = DocumentsDocumentIdEditRouteImport.update({
  id: '/documents/$documentId/edit',
  path: '/documents/$documentId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdOrganizeRoute =
  DocumentsDocumentIdOrganizeRouteImport.update({
    id: '/documents/$documentId/organize',
    path: '/documents/$documentId/organize',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-tools': typeof AllToolsRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/header-footer': typeof HeaderFooterRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/page-numbers': typeof PageNumbersRoute
  '/protect': typeof ProtectRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/split': typeof SplitRoute
  '/trash': typeof TrashRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
  '/edit/$sessionId': typeof EditSessionIdRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/split': typeof ToolsSplitRoute
  '/documents/': typeof DocumentsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/organize': typeof DocumentsDocumentIdOrganizeRoute
  '/documents/$documentId/': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-tools': typeof AllToolsRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/header-footer': typeof HeaderFooterRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/page-numbers': typeof PageNumbersRoute
  '/protect': typeof ProtectRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/split': typeof SplitRoute
  '/trash': typeof TrashRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
  '/edit/$sessionId': typeof EditSessionIdRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/split': typeof ToolsSplitRoute
  '/documents': typeof DocumentsIndexRoute
  '/edit': typeof EditIndexRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/organize': typeof DocumentsDocumentIdOrganizeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-tools': typeof AllToolsRoute
  '/compress': typeof CompressRoute
  '/convert': typeof ConvertRoute
  '/header-footer': typeof HeaderFooterRoute
  '/merge': typeof MergeRoute
  '/metadata': typeof MetadataRoute
  '/ocr': typeof OcrRoute
  '/page-numbers': typeof PageNumbersRoute
  '/protect': typeof ProtectRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/split': typeof SplitRoute
  '/trash': typeof TrashRoute
  '/unlock': typeof UnlockRoute
  '/watermark': typeof WatermarkRoute
  '/edit/$sessionId': typeof EditSessionIdRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/split': typeof ToolsSplitRoute
  '/documents/': typeof DocumentsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/documents/$documentId/edit': typeof DocumentsDocumentIdEditRoute
  '/documents/$documentId/organize': typeof DocumentsDocumentIdOrganizeRoute
  '/documents/$documentId/': typeof DocumentsDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-tools'
    | '/compress'
    | '/convert'
    | '/header-footer'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/page-numbers'
    | '/protect'
    | '/recent'
    | '/settings'
    | '/split'
    | '/trash'
    | '/unlock'
    | '/watermark'
    | '/edit/$sessionId'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/split'
    | '/documents/'
    | '/edit/'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/organize'
    | '/documents/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-tools'
    | '/compress'
    | '/convert'
    | '/header-footer'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/page-numbers'
    | '/protect'
    | '/recent'
    | '/settings'
    | '/split'
    | '/trash'
    | '/unlock'
    | '/watermark'
    | '/edit/$sessionId'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/split'
    | '/documents'
    | '/edit'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/organize'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/all-tools'
    | '/compress'
    | '/convert'
    | '/header-footer'
    | '/merge'
    | '/metadata'
    | '/ocr'
    | '/page-numbers'
    | '/protect'
    | '/recent'
    | '/settings'
    | '/split'
    | '/trash'
    | '/unlock'
    | '/watermark'
    | '/edit/$sessionId'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/split'
    | '/documents/'
    | '/edit/'
    | '/documents/$documentId/edit'
    | '/documents/$documentId/organize'
    | '/documents/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllToolsRoute: typeof AllToolsRoute
  CompressRoute: typeof CompressRoute
  ConvertRoute: typeof ConvertRoute
  HeaderFooterRoute: typeof HeaderFooterRoute
  MergeRoute: typeof MergeRoute
  MetadataRoute: typeof MetadataRoute
  OcrRoute: typeof OcrRoute
  PageNumbersRoute: typeof PageNumbersRoute
  ProtectRoute: typeof ProtectRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  SplitRoute: typeof SplitRoute
  TrashRoute: typeof TrashRoute
  UnlockRoute: typeof UnlockRoute
  WatermarkRoute: typeof WatermarkRoute
  EditSessionIdRoute: typeof EditSessionIdRoute
  ToolsCompressRoute: typeof ToolsCompressRoute
  ToolsMergeRoute: typeof ToolsMergeRoute
  ToolsOcrRoute: typeof ToolsOcrRoute
  ToolsSplitRoute: typeof ToolsSplitRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  EditIndexRoute: typeof EditIndexRoute
  DocumentsDocumentIdEditRoute: typeof DocumentsDocumentIdEditRoute
  DocumentsDocumentIdOrganizeRoute: typeof DocumentsDocumentIdOrganizeRoute
  DocumentsDocumentIdIndexRoute: typeof DocumentsDocumentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-tools': {
      id: '/all-tools'
      path: '/all-tools'
      fullPath: '/all-tools'
      preLoaderRoute: typeof AllToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/header-footer': {
      id: '/header-footer'
      path: '/header-footer'
      fullPath: '/header-footer'
      preLoaderRoute: typeof HeaderFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge': {
      id: '/merge'
      path: '/merge'
      fullPath: '/merge'
      preLoaderRoute: typeof MergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-numbers': {
      id: '/page-numbers'
      path: '/page-numbers'
      fullPath: '/page-numbers'
      preLoaderRoute: typeof PageNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit/'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$sessionId': {
      id: '/edit/$sessionId'
      path: '/edit/$sessionId'
      fullPath: '/edit/$sessionId'
      preLoaderRoute: typeof EditSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress': {
      id: '/tools/compress'
      path: '/tools/compress'
      fullPath: '/tools/compress'
      preLoaderRoute: typeof ToolsCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge': {
      id: '/tools/merge'
      path: '/tools/merge'
      fullPath: '/tools/merge'
      preLoaderRoute: typeof ToolsMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ocr': {
      id: '/tools/ocr'
      path: '/tools/ocr'
      fullPath: '/tools/ocr'
      preLoaderRoute: typeof ToolsOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split': {
      id: '/tools/split'
      path: '/tools/split'
      fullPath: '/tools/split'
      preLoaderRoute: typeof ToolsSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId/': {
      id: '/documents/$documentId/'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof DocumentsDocumentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId/edit': {
      id: '/documents/$documentId/edit'
      path: '/documents/$documentId/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof DocumentsDocumentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId/organize': {
      id: '/documents/$documentId/organize'
      path: '/documents/$documentId/organize'
      fullPath: '/documents/$documentId/organize'
      preLoaderRoute: typeof DocumentsDocumentIdOrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllToolsRoute: AllToolsRoute,
  CompressRoute: CompressRoute,
  ConvertRoute: ConvertRoute,
  HeaderFooterRoute: HeaderFooterRoute,
  MergeRoute: MergeRoute,
  MetadataRoute: MetadataRoute,
  OcrRoute: OcrRoute,
  PageNumbersRoute: PageNumbersRoute,
  ProtectRoute: ProtectRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  SplitRoute: SplitRoute,
  TrashRoute: TrashRoute,
  UnlockRoute: UnlockRoute,
  WatermarkRoute: WatermarkRoute,
  EditSessionIdRoute: EditSessionIdRoute,
  ToolsCompressRoute: ToolsCompressRoute,
  ToolsMergeRoute: ToolsMergeRoute,
  ToolsOcrRoute: ToolsOcrRoute,
  ToolsSplitRoute: ToolsSplitRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  EditIndexRoute: EditIndexRoute,
  DocumentsDocumentIdEditRoute: DocumentsDocumentIdEditRoute,
  DocumentsDocumentIdOrganizeRoute: DocumentsDocumentIdOrganizeRoute,
  DocumentsDocumentIdIndexRoute: DocumentsDocumentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
